title: minho blog
logo: profile.jpg
email: radlohead@naver.com
description: "웹프론트엔드에 관한 IT기술을 다루는 minho blog 입니다. 현재 frone-end 취업을 희망하고 있습니다. email: radlohead@naver.com"
base_url: ""
url: "http://radlohead.github.io"
author :
  name :   
  email : radlohead@naver.com

encoding: utf-8
excerpt_separator : <!--more-->
tags_dir: tags
categories_dir: categories

# gems: [jekyll-paginate, jekyll-gist]
paginate: 5
# paginate_path: "page:num"

google_analytics : 'UA-8647285-2'

twitter_username: saltfactory
github_username:  saltfactory
facebook_username: salthub
facebook_admins_id: "1825058169"
facebook_app_id: "271162092926857"
disqus_shortname: saltfactoryblog

comments:
  disqus: true
  facebook: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  extensions:
    - autolink

# markdown: redcarpet
# redcarpet:
#   extensions: ["no_intra_emphasis", "tables", "autolink", "fenced_code_blocks", "strikethrough"]
# highlighter: pygments

permalink: none

# safe: false # if using alias is safe:false
#safe: true
#lsi: false

gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
  - jekyll-feed
  # - jekyll-img-converter
  # - jekyll-coffeescript
